services:

  wordpress:
    image: stephenmiracle/frankenwp:latest
    restart: always
    ports:
      - "8094:80" # HTTP
      # - "80:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP/3
    environment:
      SERVER_NAME: ${SERVER_NAME:-:80}
      WORDPRESS_DB_HOST: ${DB_HOST:-db}
      WORDPRESS_DB_USER: ${DB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-examplepass}
      WORDPRESS_DB_NAME: ${DB_NAME:-exampledb}
      WORDPRESS_DEBUG: ${WP_DEBUG:-true}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX:-wp_}
      CACHE_AGE: ${CACHE_AGE:-8000}
      STATIC_CACHE_AGE: ${STATIC_CACHE_AGE:-8000}
      CADDY_GLOBAL_OPTIONS: |
        email myemail@sample.com
        auto_https disable_redirects
        debug
      # WORDPRESS_CONFIG_EXTRA: |
      #     define('WP_SITEURL', '');
      #     define('WP_HOME', '');
          
    volumes:
      - ./wp-content:/var/www/html/wp-content

    depends_on:
      - db
    tty: true

  db:
    image: mariadb:latest
    restart: always
    ports:
      - ${LOCAL_DB_PORT:-3309}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME:-exampledb}
      MYSQL_USER: ${DB_USER:-exampleuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-examplepass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    volumes:
      - wpdbv:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${LOCAL_PHPMYADMIN_PORT:-8096}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    depends_on:
      - db

volumes:
  wpdbv:
